---

- hosts: localhost
  tasks:
    - name: Hello
      setup:
      register: hello_output
      environment:
        ANSIBLE_ROLES_PATH: "{{ '/tmp/obedin-test:' + lookup('env', ANSIBLE_ROLES_PATH') }}"
    - debug:
        msg: "{{ ansible_env }}"

