---

- hosts: localhost
  tasks:
    - name: Hello
      setup:
      register: hello_output
    - debug:
        var: inventory_dir
    - shell: find "{{ inventory_dir }}"
    - shell: cat "{{ inventory_dir }}/env/*"

