---

- hosts: localhost
  tasks:
    - name: Hello
      setup:
      register: hello_output
      environment:
        ANSIBLE_ROLES_PATH: "{{ '/tmp/obedin-test' }}"
    - debug:
        msg: "{{ hello_output }}"

