---

- hosts: csr_host
  vars:
    file_lookup: "tasks/main.yml"
  tasks:
    - debug:
        msg: "{{ ((ansible_roles_path + file_lookup) | fileglob) }}"
    - include_role:
        name: "{{ item[:-(file_lookup|length)] }}"
      with_items: "{{ (ansible_roles_path + file_lookup) | fileglob }}" 

