---

- hosts: csr_host
  vars:
    file_lookup: "tasks/main.yml"
  tasks:
    - include_role:
        name: "{{ item[:-(file_lookup|length)] }}"
      with_items: "{{ (ansible_roles_path + '/certs/generate-csr/' + file_lookup) | fileglob }}" 

