---

name: Create Release

on:
  repository_dispatch:
    types: [release-command]
# release:
#   types: 
#     - created
      
jobs:
  prep-env:
    runs-on: ubuntu-latest
    env:
      MainVersion: ${{ github.event.client_payload.slash_command.main }}
      PatchReleaseVersion: ${{ github.event.client_payload.slash_command.patch-release }}
    steps:
    - name: Print release
      run: |
        echo This is the release: ${ MainVersion } and ${ PatchReleaseVersion }
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Changelog
        id: gh_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/workflow-config/changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: thebritican/fetch-latest-release@v2.0.0
        id: latest_release
        with:
          github_token: ${{ github.token }}
      - name: Update release with changelog
        uses: tubone24/update_release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: "${{ steps.latest_release.outputs.body }}\n\n\ ${{ steps.gh_changelog.outputs.changelog }}"

